kamikaze_traj_gen_configs:
  attempts_per_goal: 2
  controller_multipliers:
  - 0.5
  - 0.75
  - 1.0
  max_safe_trajs: 1
safe_traj_gen_configs:
  goal_areas:
  - - 116
    - -4.25
  - - 118
    - -4.25
  goal_margins:
  - 0.5
  - 0.25
  initial_state:
  - 120
  - 3
  - 100
  - -1.7
  - 0
  - 3
  samples_per_goal: 2
